### ISSUE TITLE
Wrong name on LICENSE

### ISSUE THREAD

**Issue by RafaelEstevamReis** [isaaccandido/JSONStorage#1]
https://github.com/a6576171/JSONStorage/blob/f182bdc52b033f32c5857b4647c35e5ce3e003d8/license#L5

**Comment by isaaccandido** [comment]
Holy crap

**Comment by isaaccandido** [comment]
Somebody else's gonna get my beer!

**Comment by isaaccandido** [comment]
Fixed, I get the beers now
